### ISSUE TITLE
Refactor MainWindow

### ISSUE THREAD

**Issue by WatkingStudio** [WatkingStudio/Tournament-Creator#14]
**Brief Description**
Refactor the Main Window class

**Checklist**
- [x] Remove the comment about reducing the size of the .json file
- [x] .cpp Line 90 onwards - Set the for loop value to be 'const'
- [x] Rename the QJsonObject variables to have better names
- [x] .cpp Line 151 - Don't terminate, instead create an error message box
- [x] .cpp Line 21 - Create an InitialiseResultComboBox() function

**Detailed Description**
*If further detail is required for this issue please provide it here*

**Additional Info**
*If there is any additional information required put it here*

**Comment by JelleVos1** [comment]
Could you please assign this issue to me? I would like to try and complete this.

**Comment by WatkingStudio** [comment]
> 
> 
> Could you please assign this issue to me? I would like to try and complete this.

Hi, thanks for the interest in the project. Currently these projects are just my personal projects which I'm working on, that can be viewed and cloned by the public.

I'm doing some improvements on them at the moment, but I'm currently not looking for external contributions, I thought I had set up the settings for this correctly but it seems that I didn't so I apologize for that. If you do wish to clone the project and work on it yourself then you are more than welcome to.

As you can see I'm currently in the process of refactoring the project, so over the next few weeks there will be some updates to improve the code, so be sure to check back if you are interested in seeing an updated version of the project.

Once again sorry for any inconvenience and confusion caused, wishing you all the best with your coding ventures.

WatkingStudio
